-- place.category 채우기. 몇 번을 다시 실행해도 안전 (WHERE category IS NULL 가드).
UPDATE place
SET category = CASE name
  WHEN '대릉원' THEN 'HISTORY_CULTURE'
  WHEN '천마총' THEN 'HISTORY_CULTURE'
  WHEN '첨성대' THEN 'HISTORY_CULTURE'
  WHEN '동궁과 월지' THEN 'HISTORY_CULTURE'
  WHEN '국립경주박물관' THEN 'HISTORY_CULTURE'
  WHEN '경주 월성' THEN 'HISTORY_CULTURE'
  WHEN '계림' THEN 'HISTORY_CULTURE'
  WHEN '분황사' THEN 'HISTORY_CULTURE'
  WHEN '불국사' THEN 'WORLD_HERITAGE'
  WHEN '양동마을' THEN 'WORLD_HERITAGE'
  WHEN '옥산서원' THEN 'WORLD_HERITAGE'
  WHEN '보문관광단지' THEN 'NATURE_HEALING'
  WHEN '대왕암' THEN 'NATURE_HEALING'
  WHEN '양남 주상절리 파도소리길' THEN 'NATURE_HEALING'
  WHEN '경주 남산' THEN 'NATURE_HEALING'
END
WHERE category IS NULL;
